### ISSUE TITLE
No 'data/hospital/vocab_zh.pth' file?

### ISSUE THREAD

**Issue by XinMing0411** [RicherMans/AudioCaption#3]

**Comment by XinMing0411** [comment]
Dear sir I dont find the copyark2hdf5.py file

**Comment by RicherMans** [comment]
Likely since we mostly switched to h5py. Sorry, the README is a bit outdated, but the code is used for research still, so it should mostly work.

**Comment by XinMing0411** [comment]
谢谢~

**Comment by XinMing0411** [comment]
Another problems
1.I downloaded the data set of the car, but I didn't find the caption file in the data set.
2.The download link of the hospital dataset is invalid

**Comment by RicherMans** [comment]
> Another problems
> 1.I downloaded the data set of the car, but I didn't find the caption file in the data set.
> 2.The download link of the hospital dataset is invalid

Thanks, we didn't notice that actually, we initially intended to upload the data ... but I guess forgot that. 


@wsntxxn 能不能帮我看一下 ？:)

**Comment by wsntxxn** [comment]
The caption files are provided in `data/car/*.json`. I will upload to Zenodo later today.
For the hospital dataset, I will also update to Zenodo.

**Comment by RicherMans** [comment]
> The caption files are provided in `data/car/*.json`. I will upload to Zenodo later today.
> For the hospital dataset, I will also update to Zenodo.

Might want to update the README.md ?

**Comment by XinMing0411** [comment]
> The caption files are provided in `data/car/*.json`. I will upload to Zenodo later today.
> For the hospital dataset, I will also update to Zenodo.

谢谢

**Comment by wsntxxn** [comment]
All data are available in Zenodo now.
README.md has also been updated. I check the whole pipeline.
